@extends('layouts.app')

@section('title', $template ? 'Edit diagnostic template '.$template->template_code : 'Create diagnostic template')

@section('content')
@php($editing = $version !== null)
<section class="container sb-record" id="diagnostic-template-editor">
    <div class="record-header"><div><h1>{{ $editing ? 'Edit draft diagnostic template' : 'Create diagnostic template' }}</h1><p class="text-muted">Only draft content is editable. Sessions keep the published snapshot they started with.</p></div><a class="btn btn-default" href="{{ route('recommerce.diagnostic.templates.index') }}">Back</a></div>
    @if(session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
    @foreach($errors->all() as $error)<div class="alert alert-warning" role="alert">{{ $error }}</div>@endforeach
    @php($action = $editing ? route('recommerce.diagnostic.templates.update', [$template->id, $version->id]) : route('recommerce.diagnostic.templates.store'))
    <form method="POST" action="{{ $action }}" id="diagnostic-template-form">@csrf @if($editing) @method('PUT') @endif
        <div class="record-card"><h2>Template identity</h2><div class="card-body"><div class="row"><div class="col-sm-3 form-group"><label for="template-code">Template code</label><input id="template-code" name="template_code" class="form-control" value="{{ old('template_code', $template->template_code ?? '') }}" maxlength="64" required></div><div class="col-sm-5 form-group"><label for="template-name">Name</label><input id="template-name" name="name" class="form-control" value="{{ old('name', $template->name ?? '') }}" maxlength="160" required></div><div class="col-sm-2 form-group"><label for="template-category">Category</label><input id="template-category" name="category_code" class="form-control" value="{{ old('category_code', $template->category_code ?? '') }}" maxlength="32"></div><div class="col-sm-2 form-group"><label for="template-job-type">Job type</label><select id="template-job-type" name="job_type" class="form-control"><option value="">Any</option><option value="CUSTOMER_REPAIR" {{ old('job_type', $template->job_type ?? '') === 'CUSTOMER_REPAIR' ? 'selected' : '' }}>Customer repair</option><option value="INTERNAL_REFURBISHMENT" {{ old('job_type', $template->job_type ?? '') === 'INTERNAL_REFURBISHMENT' ? 'selected' : '' }}>Internal refurbishment</option></select></div></div>
            @if(! $editing)<div class="form-group"><label for="template-location">Branch scope</label><select id="template-location" name="location_id" class="form-control" required><option value="">Choose an authorized branch</option>@foreach($locations as $location)<option value="{{ $location->id }}" {{ (string) old('location_id') === (string) $location->id ? 'selected' : '' }}>{{ $location->name }}</option>@endforeach</select></div>@else<input type="hidden" name="location_id" value="{{ $template->location_id }}">@endif
        </div></div>
        <div class="record-card"><h2>Checks</h2><div class="card-body"><p class="text-muted">Use one row per check. Drag rows to reorder before saving.</p><div id="diagnostic-check-list">
            @php($checks = old('checks', $version ? $version->checks->map(fn($check) => ['check_key'=>$check->check_key,'label'=>$check->label,'outcome_type'=>$check->outcome_type,'unit'=>$check->unit,'minimum_value'=>$check->minimum_value,'maximum_value'=>$check->maximum_value,'allowed_outcomes'=>implode(', ', $check->allowed_outcomes_json ?: []),'is_required'=>$check->is_required,'evidence_required'=>$check->evidence_required])->all() : [['check_key'=>'','label'=>'','outcome_type'=>'STATUS','unit'=>'','minimum_value'=>'','maximum_value'=>'','allowed_outcomes'=>'PASS, FAIL, NOT_APPLICABLE','is_required'=>1,'evidence_required'=>0]]))
            @foreach($checks as $index => $check)<div class="diagnostic-check-row well well-sm" draggable="true"><div class="row"><div class="col-sm-2"><label>Key<input name="checks[{{ $index }}][check_key]" class="form-control" value="{{ $check['check_key'] ?? '' }}" maxlength="64" required></label></div><div class="col-sm-3"><label>Label<input name="checks[{{ $index }}][label]" class="form-control" value="{{ $check['label'] ?? '' }}" maxlength="160" required></label></div><div class="col-sm-2"><label>Type<select name="checks[{{ $index }}][outcome_type]" class="form-control"><option {{ ($check['outcome_type'] ?? '') === 'STATUS' ? 'selected' : '' }}>STATUS</option><option {{ ($check['outcome_type'] ?? '') === 'TEXT' ? 'selected' : '' }}>TEXT</option><option {{ ($check['outcome_type'] ?? '') === 'NUMERIC' ? 'selected' : '' }}>NUMERIC</option></select></label></div><div class="col-sm-2"><label>Unit<input name="checks[{{ $index }}][unit]" class="form-control" value="{{ $check['unit'] ?? '' }}" maxlength="24"></label></div><div class="col-sm-1"><label>Min<input name="checks[{{ $index }}][minimum_value]" class="form-control" type="number" step="any" value="{{ $check['minimum_value'] ?? '' }}"></label></div><div class="col-sm-1"><label>Max<input name="checks[{{ $index }}][maximum_value]" class="form-control" type="number" step="any" value="{{ $check['maximum_value'] ?? '' }}"></label></div><div class="col-sm-1"><button class="btn btn-link diagnostic-remove" type="button" aria-label="Remove diagnostic check">Remove</button></div></div><div class="row"><div class="col-sm-8"><label>Allowed outcomes (comma separated)<input name="checks[{{ $index }}][allowed_outcomes]" class="form-control" value="{{ is_array($check['allowed_outcomes'] ?? null) ? implode(', ', $check['allowed_outcomes']) : ($check['allowed_outcomes'] ?? '') }}" maxlength="500"></label></div><div class="col-sm-2"><label><input name="checks[{{ $index }}][is_required]" type="checkbox" value="1" {{ !empty($check['is_required']) ? 'checked' : '' }}> Required</label></div><div class="col-sm-2"><label><input name="checks[{{ $index }}][evidence_required]" type="checkbox" value="1" {{ !empty($check['evidence_required']) ? 'checked' : '' }}> Evidence required</label></div></div></div>@endforeach
        </div><button class="btn btn-default" type="button" id="diagnostic-add-check">Add check</button> <button class="btn btn-primary" type="submit">Save draft</button></div></div>
    </form>
    @if($editing && $version->status === 'DRAFT')<form method="POST" action="{{ route('recommerce.diagnostic.templates.publish', [$template->id, $version->id]) }}" style="display:inline">@csrf<button class="btn btn-success" type="submit">Publish immutable version</button></form>@elseif($editing && $version->status === 'PUBLISHED')<form method="POST" action="{{ route('recommerce.diagnostic.templates.retire', [$template->id, $version->id]) }}" style="display:inline">@csrf<button class="btn btn-warning" type="submit">Retire version</button></form>@endif
</section>
<script>
(function(){var list=document.getElementById('diagnostic-check-list');var add=document.getElementById('diagnostic-add-check');if(!list||!add)return;function renumber(){list.querySelectorAll('.diagnostic-check-row').forEach(function(row,index){row.querySelectorAll('[name]').forEach(function(input){input.name=input.name.replace(/checks\[\d+\]/,'checks['+index+']');});});}add.addEventListener('click',function(){var row=list.querySelector('.diagnostic-check-row').cloneNode(true);row.querySelectorAll('input').forEach(function(input){if(input.type==='checkbox')input.checked=input.name.indexOf('is_required')>=0;else input.value='';});row.querySelector('select').value='STATUS';list.appendChild(row);renumber();});list.addEventListener('click',function(event){if(event.target.classList.contains('diagnostic-remove')){var rows=list.querySelectorAll('.diagnostic-check-row');if(rows.length>1){event.target.closest('.diagnostic-check-row').remove();renumber();}}});var drag=null;list.addEventListener('dragstart',function(event){drag=event.target.closest('.diagnostic-check-row');});list.addEventListener('dragover',function(event){event.preventDefault();var target=event.target.closest('.diagnostic-check-row');if(drag&&target&&drag!==target){target.parentNode.insertBefore(drag,target);renumber();}});})();
</script>
@endsection
