@php
    $money=static fn($value)=>number_format((float)$value,2);
    $quoteSpec=$selectedQuote?(array)$selectedQuote->specifications_json:[];
    $quoteCondition=$selectedQuote?(array)$selectedQuote->condition_json:[];
    $quoteCustomerId=$selectedQuote?$selectedQuote->customer_contact_id:old('customer_contact_id');
    $quoteExpired=$selectedQuote&&$selectedQuote->isExpired();
    $checks=['display'=>'Display','keyboard'=>'Keyboard','trackpad'=>'Trackpad','wifi'=>'Wi-Fi','bluetooth'=>'Bluetooth','webcam'=>'Webcam','microphone'=>'Microphone','speakers'=>'Speakers','usb_ports'=>'USB ports','hdmi_output'=>'HDMI','charging'=>'Charging','power_on'=>'Power on','storage_health'=>'Storage health'];
    $photoPurposes=['FRONT_OPEN'=>'Front / open','KEYBOARD_PALMREST'=>'Keyboard','POWERED_SCREEN'=>'Screen on','BOTTOM_REAR'=>'Bottom','SERIAL_LABEL'=>'Serial label','DEFECT_DAMAGE'=>'Damage'];
@endphp

@if($selectedQuote)
<div class="sb-ti-panel">
    <div class="sb-ti-panel-head"><div><h2>Quick Quote QQ-{{ str_pad($selectedQuote->id,5,'0',STR_PAD_LEFT) }}</h2><p>{{ data_get($quoteSpec,'brand') }} {{ data_get($quoteSpec,'model') }} · valid until {{ $selectedQuote->expires_at->format('d M Y') }}</p></div><span class="sb-ti-badge {{ $quoteExpired?'warning':'info' }}">{{ $quoteExpired?'Revaluation required':'Customer considering' }}</span></div>
    <div class="sb-ti-panel-body"><div class="row"><div class="col-sm-4"><div class="sb-ti-recommended"><span>Estimated acquisition range</span><strong style="font-size:27px">RM {{ $money($selectedQuote->estimated_low_amount) }}–{{ $money($selectedQuote->estimated_high_amount) }}</strong></div></div><div class="col-sm-4"><div class="sb-ti-summary"><div class="sb-ti-summary-row"><span>Customer wants</span><strong>{{ $selectedQuote->customer_expected_amount===null?'Not sure':'RM '.$money($selectedQuote->customer_expected_amount) }}</strong></div><div class="sb-ti-summary-row"><span>Range gap</span><strong>{{ $selectedQuote->customer_expected_amount===null?'—':'RM '.$money(max(0,(float)$selectedQuote->customer_expected_amount-(float)$selectedQuote->estimated_high_amount)).'+' }}</strong></div></div></div><div class="col-sm-4"><div class="sb-ti-callout {{ $quoteExpired?'warning':'' }}"><strong>Subject to full inspection</strong><br>{{ $quoteExpired?'This estimate is expired. Save a new Quick Quote; the original remains in history.':'Continue below when the customer wants a complete inspection and formal offer.' }}</div>
@if(!$quoteExpired)<details><summary>Customer declined</summary><form method="post" action="{{ route('recommerce.tradeins.quick_quotes.decline',$selectedQuote->id) }}" style="margin-top:8px">
@csrf<select aria-label="reason_code" class="form-control" name="reason_code"><option value="OFFER_TOO_LOW">Offer too low</option><option value="CUSTOMER_EXPECTED_MORE">Customer expected more</option><option value="COMPETITOR_OFFERED_MORE">Competitor offered more</option><option value="CUSTOMER_DECIDED_NOT_TO_SELL">Changed mind</option><option value="PRICE_CHECK_ONLY">Price check only</option><option value="OTHER">Other</option></select><input aria-label="reason" class="form-control" style="margin-top:6px" name="reason" required maxlength="255" placeholder="Short outcome note"><button class="btn btn-default btn-block" style="margin-top:6px" type="submit">Close as Customer Declined</button></form></details>
@endif</div></div></div>
</div>
@endif

<details class="sb-ti-panel" {{ !$selectedQuote?'open':'' }}>
    <summary class="sb-ti-panel-head"><div><h2>{{ $quoteExpired?'Create a replacement Quick Quote':'Quick Quote' }}</h2><p>A fast, non-binding range. It does not create a Device or post a purchase.</p></div><span class="sb-ti-badge info">2–3 minutes</span></summary>
    <div class="sb-ti-panel-body"><form method="post" action="{{ route('recommerce.tradeins.quick_quotes.store') }}" id="quick-quote-form">
@csrf<input aria-label="command_uuid" type="hidden" name="command_uuid" value="{{ (string)\Illuminate\Support\Str::uuid() }}">
@if($quoteExpired)<input aria-label="supersedes_quote_id" type="hidden" name="supersedes_quote_id" value="{{ $selectedQuote->id }}">
@endif
        <div class="sb-ti-choice-grid" style="margin-bottom:14px"><div class="sb-ti-choice"><input aria-label="acquisition_type" id="qq-sell" type="radio" name="acquisition_type" value="SELL_TO_SAVERBRO" {{ !$selectedQuote||$selectedQuote->acquisition_type==='SELL_TO_SAVERBRO'?'checked':'' }}><label for="qq-sell"><strong>Sell Device</strong><span>Customer receives settlement for the Device.</span></label></div><div class="sb-ti-choice"><input aria-label="acquisition_type" id="qq-trade" type="radio" name="acquisition_type" value="TRADE_IN" {{ $selectedQuote&&$selectedQuote->acquisition_type==='TRADE_IN'?'checked':'' }}><label for="qq-trade"><strong>Trade-In</strong><span>Value may be linked to a separate SaverBro sale.</span></label></div></div>
        <div class="row"><div class="col-md-4 form-group"><label>Seller (optional for first estimate)</label><select aria-label="customer_contact_id" class="form-control" name="customer_contact_id"><option value="">Not selected yet</option>
@foreach($customers as $customer)<option value="{{ $customer->id }}"
@selected((string)$quoteCustomerId===(string)$customer->id)>{{ $customer->name }}{{ $customer->mobile?' · '.$customer->mobile:'' }}</option>
@endforeach</select></div><div class="col-md-4 form-group"><label>Seller name if new</label><input aria-label="seller_name" class="form-control" name="seller_name" value="{{ $selectedQuote?$selectedQuote->seller_name_snapshot:'' }}" maxlength="255"></div><div class="col-md-4 form-group"><label>Phone</label><input aria-label="seller_phone" class="form-control" name="seller_phone" value="{{ $selectedQuote?$selectedQuote->seller_phone_snapshot:'' }}" maxlength="80"></div></div>
        <div class="row"><div class="col-md-4 form-group"><label>Catalogue match</label><select aria-label="variation_id" class="form-control" name="variation_id" required><option value="">Choose product</option>
@foreach($variations as $variation)<option value="{{ $variation->id }}"
@selected($selectedQuote&&(int)$selectedQuote->variation_id===(int)$variation->id)>{{ $variation->product->name }} · {{ $variation->name?:'Default' }}</option>
@endforeach</select></div><div class="col-md-4 form-group"><label>Brand</label><input aria-label="brand" class="form-control" name="brand" required maxlength="100" value="{{ data_get($quoteSpec,'brand') }}"></div><div class="col-md-4 form-group"><label>Model</label><input aria-label="model" class="form-control" name="model" required maxlength="160" value="{{ data_get($quoteSpec,'model') }}"></div></div>
        <div class="row">
@foreach(['cpu'=>'CPU','ram'=>'RAM','storage'=>'Storage','gpu'=>'GPU'] as $name=>$label)<div class="col-sm-3 form-group"><label>{{ $label }}</label><input aria-label="{{ $name }}" class="form-control" name="{{ $name }}" maxlength="160" value="{{ data_get($quoteSpec,$name) }}"></div>
@endforeach</div>
        <div class="row"><div class="col-md-3 form-group"><label>Cosmetic grade</label><select aria-label="cosmetic_grade" class="form-control" name="cosmetic_grade" required><option value="">Choose grade</option>
@foreach(['A','B','C','D'] as $grade)<option value="{{ $grade }}"
@selected(data_get($quoteCondition,'cosmetic_grade')===$grade)>Grade {{ $grade }}</option>
@endforeach</select></div><div class="col-md-3 form-group"><label>Battery health %</label><input aria-label="battery_health_percent" class="form-control" type="number" min="0" max="100" step="0.1" name="battery_health_percent" value="{{ data_get($quoteCondition,'battery_health_percent') }}"></div><div class="col-md-3 form-group"><label>SaverBro expected resale</label><input aria-label="expected_resale_amount" class="form-control" type="number" min="0.01" step="0.01" name="expected_resale_amount" placeholder="Uses catalogue price if blank"></div><div class="col-md-3 form-group"><label>Customer expected price</label><input aria-label="customer_expected_amount" class="form-control" type="number" min="0" step="0.01" name="customer_expected_amount" value="{{ $selectedQuote?$selectedQuote->customer_expected_amount:'' }}"><label style="font-weight:400;margin-top:5px"><input aria-label="customer_expected_unknown" type="checkbox" name="customer_expected_unknown" value="1" {{ $selectedQuote&&$selectedQuote->customer_expected_unknown?'checked':'' }}> Not sure</label></div></div>
        <div class="row"><div class="col-md-9 form-group"><label>Major defects</label><input aria-label="major_defects" class="form-control" name="major_defects" maxlength="1000" value="{{ data_get($quoteCondition,'major_defects') }}" placeholder="Only the major issue affecting the estimate"></div><div class="col-md-3 form-group"><label style="margin-top:31px"><input aria-label="charger_included" type="checkbox" name="charger_included" value="1" {{ data_get($quoteCondition,'charger_included')?'checked':'' }}> Charger included</label></div></div>
        <button class="btn btn-primary" type="submit">Calculate & save Quick Quote</button> <span class="text-muted" style="margin-left:8px">Subject to full inspection.</span>
    </form></div>
</details>

@if(!$quoteExpired)
<div class="sb-ti-workspace">
<main class="sb-ti-workspace-main"><form method="post" action="{{ route('recommerce.tradeins.store') }}" enctype="multipart/form-data" autocomplete="off" id="tradein-full-form" novalidate>
@csrf<input aria-label="command_uuid" type="hidden" name="command_uuid" value="{{ (string)\Illuminate\Support\Str::uuid() }}">
@if($selectedQuote)<input aria-label="quick_quote_id" type="hidden" name="quick_quote_id" value="{{ $selectedQuote->id }}">
@endif<input aria-label="category_code" type="hidden" name="category_code" value="LAPTOP">
    <div class="sb-ti-stepper" role="tablist"><button class="active" type="button" data-ti-step="0">1 Intake</button><button type="button" data-ti-step="1">2 Check</button><button type="button" data-ti-step="2">3 Deal</button><button type="button" data-ti-step="3">4 Close</button></div>
    <fieldset class="sb-ti-step active" data-ti-panel="0">
        <div class="sb-ti-section"><h3>Acquisition mode</h3><p class="sb-ti-section-intro">Only currently supported single-Device paths are shown.</p><div class="sb-ti-choice-grid"><div class="sb-ti-choice"><input aria-label="acquisition_type" id="full-sell" type="radio" name="acquisition_type" value="SELL_TO_SAVERBRO" {{ !$selectedQuote||$selectedQuote->acquisition_type==='SELL_TO_SAVERBRO'?'checked':'' }}><label for="full-sell"><strong>Sell Device</strong><span>Customer receives settlement for this Device.</span></label></div><div class="sb-ti-choice"><input aria-label="acquisition_type" id="full-trade" type="radio" name="acquisition_type" value="TRADE_IN" {{ $selectedQuote&&$selectedQuote->acquisition_type==='TRADE_IN'?'checked':'' }}><label for="full-trade"><strong>Trade-In</strong><span>Value is linked to, not discounted from, a separate sale.</span></label></div></div></div>
        <div class="sb-ti-section"><h3>Seller</h3><p class="sb-ti-section-intro">Search an existing customer or reveal the fields for a new seller.</p><div class="form-group"><label>Existing seller</label><select aria-label="customer_contact_id" id="full-seller" class="form-control" name="customer_contact_id"><option value="">+ Create New Seller</option>
@foreach($customers as $customer)<option value="{{ $customer->id }}" data-phone="{{ $customer->mobile }}"
@selected((string)$quoteCustomerId===(string)$customer->id)>{{ $customer->name }}{{ $customer->mobile?' · '.$customer->mobile:'' }}</option>
@endforeach</select></div><div id="new-seller-fields" class="row"><div class="col-sm-6 form-group"><label>Seller name</label><input aria-label="seller_name" class="form-control" name="seller_name" maxlength="255" value="{{ $selectedQuote&&!$selectedQuote->customer_contact_id?$selectedQuote->seller_name_snapshot:old('seller_name') }}"></div><div class="col-sm-6 form-group"><label>Phone</label><input aria-label="seller_phone" class="form-control" name="seller_phone" maxlength="80" value="{{ $selectedQuote&&!$selectedQuote->customer_contact_id?$selectedQuote->seller_phone_snapshot:old('seller_phone') }}"></div></div><details><summary>Seller verification</summary><div class="form-group" style="margin-top:10px"><label>Identification reference</label><input aria-label="seller_identity_reference" class="form-control" name="seller_identity_reference" maxlength="255" autocomplete="off"><p class="help-block">Stored encrypted and never shown in acquisition tables.</p></div></details></div>
        <div class="sb-ti-section"><h3>Device Passport</h3><p class="sb-ti-section-intro">Select a recognized customer Device or create one from an exact serial, IMEI or SaverBro Device ID.</p><div class="form-group"><label>Existing Device</label><select aria-label="device_id" id="full-device" class="form-control" name="device_id"><option value="">+ New Device</option>
@foreach($devices as $device)<option value="{{ $device->id }}" data-device="{{ $device->device_code }}" data-model="{{ trim($device->brand.' '.$device->model) }}" data-state="{{ ucwords(strtolower(str_replace('_',' ',$device->lifecycle_state))) }}" data-sold-at="{{ optional($device->sold_at)->format('d M Y') }}">{{ $device->device_code }} · {{ $device->brand }} {{ $device->model }}</option>
@endforeach</select></div><div id="recognized-device" class="sb-ti-callout success" style="display:none"><strong>SaverBro Device recognized</strong><br><span id="recognized-device-text"></span><br><span id="recognized-device-history"></span><br><small>Existing Device Passport selected. No duplicate Device will be created.</small></div><div id="new-device-fields"><div class="row"><div class="col-sm-4 form-group"><label>Identifier type</label><select aria-label="identifier_type" class="form-control" name="identifier_type"><option value="SERIAL">Serial number</option><option value="IMEI">IMEI</option><option value="DEVICE_CODE">SaverBro Device ID</option></select></div><div class="col-sm-8 form-group"><label>Exact identifier</label><input aria-label="identifier_value" class="form-control" name="identifier_value" maxlength="160" placeholder="Scan or enter exact serial / IMEI / Device ID"></div></div></div><div class="row"><div class="col-sm-4 form-group"><label>Brand</label><input aria-label="laptop_brand" id="full-brand" class="form-control" name="laptop_brand" required maxlength="100" value="{{ data_get($quoteSpec,'brand',old('laptop_brand')) }}"></div><div class="col-sm-4 form-group"><label>Model</label><input aria-label="laptop_model" id="full-model" class="form-control" name="laptop_model" required maxlength="160" value="{{ data_get($quoteSpec,'model',old('laptop_model')) }}"></div><div class="col-sm-4 form-group"><label>Confirmed catalogue match</label><select aria-label="variation_id" class="form-control" name="variation_id" required><option value="">Choose product</option>
@foreach($variations as $variation)<option value="{{ $variation->id }}"
@selected($selectedQuote&&(int)$selectedQuote->variation_id===(int)$variation->id)>{{ $variation->product->name }} · {{ $variation->name?:'Default' }}</option>
@endforeach</select></div></div><div class="row">
@foreach(['cpu'=>'CPU','ram'=>'RAM','storage'=>'Storage','gpu'=>'GPU','display_size'=>'Display','operating_system'=>'Operating system'] as $name=>$label)<div class="col-sm-4 form-group"><label>{{ $label }}</label><input aria-label="laptop_{{ $name }}" class="form-control" name="laptop_{{ $name }}" maxlength="160" value="{{ data_get($quoteSpec,$name) }}"></div>
@endforeach</div></div>
    </fieldset>
    <fieldset class="sb-ti-step" data-ti-panel="1">
        <div class="sb-ti-section"><h3>Quick condition summary</h3><p class="sb-ti-section-intro">Grade supports the pricing decision; security and identity checks remain manual.</p><div class="sb-ti-grade-grid">
@foreach(['A'=>'Excellent','B'=>'Normal used condition','C'=>'Visible wear / dents','D'=>'Heavy damage'] as $grade=>$description)<div class="sb-ti-choice sb-ti-grade"><input aria-label="cosmetic_grade" id="grade-{{ $grade }}" type="radio" name="cosmetic_grade" value="{{ $grade }}" required {{ data_get($quoteCondition,'cosmetic_grade')===$grade?'checked':'' }}><label for="grade-{{ $grade }}"><strong>Grade {{ $grade }}</strong><span>{{ $description }}</span></label></div>
@endforeach</div><div class="row" style="margin-top:12px"><div class="col-sm-4 form-group"><label>Battery health %</label><input aria-label="battery_health_percent" class="form-control" type="number" min="0" max="100" step=".1" name="battery_health_percent" value="{{ data_get($quoteCondition,'battery_health_percent') }}"></div><div class="col-sm-4 form-group"><label>Battery replacement</label><select aria-label="battery_replacement_needed" class="form-control" name="battery_replacement_needed"><option value="NO">No</option><option value="CONDITIONAL">Conditional</option><option value="YES">Yes</option></select></div><div class="col-sm-4 form-group"><label>Replacement estimate</label><input aria-label="battery_replacement_estimate_amount" class="form-control" type="number" min="0" step=".01" name="battery_replacement_estimate_amount" value="0"></div></div><div class="form-group"><label>Cosmetic / major defect notes</label><textarea aria-label="cosmetic_notes" class="form-control" name="cosmetic_notes" rows="2">{{ data_get($quoteCondition,'major_defects') }}</textarea></div></div>
        <div class="sb-ti-section"><div class="clearfix"><div class="pull-left"><h3>Basic functional checks</h3><p class="sb-ti-section-intro">Use the safe preset, then change exceptions. Power, battery, identity and risk checks are not auto-passed.</p></div><button class="btn btn-default pull-right" id="basic-pass" type="button">Mark basic checks passed</button></div><div class="row">
@foreach($checks as $name=>$label)<div class="col-sm-4 form-group"><label>{{ $label }}</label><select aria-label="{{ $name }}_outcome" class="form-control" name="{{ $name }}_outcome" {{ in_array($name,['display','keyboard','trackpad','wifi','bluetooth','webcam','microphone','speakers','usb_ports','hdmi_output'],true)?'data-basic-functional=1':'' }}><option value="NOT_TESTED">Not tested</option><option value="PASS">Pass</option><option value="FAIL">Fail</option><option value="CONDITIONAL">Conditional</option></select></div>
@endforeach</div></div>
        <div class="sb-ti-section"><h3>Accessories and risk / lock checks</h3><p class="sb-ti-section-intro">These checks are never auto-passed.</p><div class="row"><div class="col-sm-5"><label><input aria-label="charger_included" type="checkbox" name="charger_included" value="1" {{ data_get($quoteCondition,'charger_included')?'checked':'' }}> Charger included</label><input aria-label="charger_type" class="form-control" name="charger_type" placeholder="Charger type / originality"><label style="margin-top:8px"><input aria-label="box_included" type="checkbox" name="box_included" value="1"> Box included</label></div><div class="col-sm-7">
@foreach(['BIOS_PASSWORD'=>'BIOS password','MDM_MANAGED'=>'MDM/company management','ACCOUNT_LOCK'=>'Account lock','COMPANY_ASSET_TAG'=>'Company asset tag','SUSPICIOUS_SERIAL'=>'Suspicious serial','OWNERSHIP_CONCERN'=>'Ownership concern'] as $value=>$label)<label class="checkbox-inline"><input aria-label="risk_flags[]" type="checkbox" name="risk_flags[]" value="{{ $value }}"> {{ $label }}</label>
@endforeach</div></div></div>
        <div class="sb-ti-section"><h3>Photo evidence</h3><p class="sb-ti-section-intro">Purpose-specific evidence stays on the Device Passport.</p><div class="row">
@foreach($photoPurposes as $value=>$label)<div class="col-sm-4 form-group"><label>{{ $label }}</label><input aria-label="photos[]" class="form-control" type="file" name="photos[]" accept="image/*"><input aria-label="photo_purpose[]" type="hidden" name="photo_purpose[]" value="{{ $value }}"></div>
@endforeach</div></div>
    </fieldset>
    <fieldset class="sb-ti-step" data-ti-panel="2">
        <div class="sb-ti-section"><h3>Market evidence</h3><p class="sb-ti-section-intro">Record external asking prices, not claimed selling prices.</p><div class="row">
@foreach([1=>'External asking evidence',2=>'Competitor / comparison'] as $number=>$label)<div class="col-sm-6"><div class="form-group"><label>{{ $label }}</label><input aria-label="market_evidence_{{ $number }}_source" class="form-control" name="market_evidence_{{ $number }}_source" required maxlength="320" placeholder="Source and comparable model/spec"></div><div class="form-group"><label>Asking price</label><input aria-label="market_evidence_{{ $number }}_amount" class="form-control evidence-amount" name="market_evidence_{{ $number }}_amount" required type="number" min="0" step=".01"></div><div class="form-group"><label>URL (optional)</label><input aria-label="market_evidence_{{ $number }}_url" class="form-control" name="market_evidence_{{ $number }}_url" type="url" maxlength="1000"></div></div>
@endforeach</div><div id="market-guidance" class="sb-ti-callout">Enter both evidence prices to establish the allowed market-reference range.</div></div>
        <div class="sb-ti-section"><h3>Deal inputs</h3><p class="sb-ti-section-intro">The server calculates the recommendation and all ceilings from the active pricing policy.</p><div class="row"><div class="col-sm-4 form-group"><label>Market reference</label><input aria-label="market_reference_amount" id="market-reference" class="form-control" name="market_reference_amount" required type="number" min="0" step=".01"></div><div class="col-sm-4 form-group"><label>SaverBro expected resale</label><input aria-label="expected_resale_amount" class="form-control" name="expected_resale_amount" required type="number" min="0" step=".01" value="{{ $selectedQuote ? number_format((float) $selectedQuote->expected_resale_amount, 2, '.', '') : '' }}"></div><div class="col-sm-4 form-group"><label>Estimated refurbishment</label><input aria-label="expected_refurbishment_amount" class="form-control" name="expected_refurbishment_amount" required type="number" min="0" step=".01" value="0"></div></div><div class="row"><div class="col-sm-6 form-group"><label>Customer expected price</label><input aria-label="customer_requested_amount" class="form-control" name="customer_requested_amount" type="number" min="0" step=".01" value="{{ $selectedQuote && $selectedQuote->customer_expected_amount !== null ? number_format((float) $selectedQuote->customer_expected_amount, 2, '.', '') : '' }}"></div><div class="col-sm-6 form-group"><label>Proposed staff offer</label><input aria-label="staff_proposed_amount" class="form-control" name="staff_proposed_amount" required type="number" min="0" step=".01" value="{{ $selectedQuote ? number_format((float) data_get($selectedQuote->pricing_snapshot_json, 'recommendation.target_acquisition_amount'), 2, '.', '') : '' }}"></div></div></div>
    </fieldset>
    <fieldset class="sb-ti-step" data-ti-panel="3">
        <div class="sb-ti-section"><h3>Seller verification and close</h3><p class="sb-ti-section-intro">This records an inspection and formal offer. Acceptance and payment happen only after Deal Desk review.</p><div class="sb-ti-callout"><strong>Accounting integrity</strong><br>Sell Device and Trade-In both create a native purchase only after an authorized user accepts the deal. Trade-In value is not represented as a sale discount.</div><div class="well" style="background:var(--sb-surface,#0b1728);border-color:var(--sb-border,#334b68)"><p>{{ $sellerDeclarationText }}</p><label><input aria-label="seller_declaration_accepted" type="checkbox" name="seller_declaration_accepted" value="1" required> Seller acknowledged this ownership declaration.</label></div><button class="btn btn-primary btn-lg" type="submit"
@disabled($variations->isEmpty())>Create Deal Recommendation</button></div>
    </fieldset>
    <div class="clearfix"><button id="ti-prev" class="btn btn-default pull-left" type="button" style="display:none">Previous</button><button id="ti-next" class="btn btn-primary pull-right" type="button">Continue to Check</button></div>
</form></main>
<aside class="sb-ti-sticky"><div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>Acquisition status</h2><p>Current step and blockers</p></div></div><div class="sb-ti-summary"><div class="sb-ti-summary-row"><span>Mode</span><strong id="side-mode">Sell Device</strong></div><div class="sb-ti-summary-row"><span>Seller</span><strong id="side-seller">Not selected</strong></div><div class="sb-ti-summary-row"><span>Device</span><strong id="side-device">Not identified</strong></div><div class="sb-ti-summary-row"><span>Current stage</span><strong id="side-stage">Intake</strong></div></div></div><div class="sb-ti-callout"><strong>What happens next?</strong><br><span id="side-next">Identify the seller and exact Device.</span></div></aside>
</div>
<script>
(function(){
var form=document.getElementById('tradein-full-form');if(!form)return;var buttons=[].slice.call(form.querySelectorAll('[data-ti-step]')),panels=[].slice.call(form.querySelectorAll('[data-ti-panel]')),index=0,names=['Intake','Check','Deal','Close'],nextCopy=['Continue to Check','Continue to Deal','Continue to Close',''];var nextHelp=['Identify the seller and exact Device.','Record condition, tests, risks and evidence.','Enter market evidence and a proposed offer.','Create the formal recommendation for Deal Desk review.'];var next=document.getElementById('ti-next'),prev=document.getElementById('ti-prev');
function show(i){index=i;buttons.forEach(function(b,n){b.classList.toggle('active',n===i)});panels.forEach(function(p,n){p.classList.toggle('active',n===i)});prev.style.display=i?'':'none';next.style.display=i===panels.length-1?'none':'';next.textContent=nextCopy[i]||'';document.getElementById('side-stage').textContent=names[i];document.getElementById('side-next').textContent=nextHelp[i]}
function valid(){var fields=panels[index].querySelectorAll('input,select,textarea');for(var i=0;i<fields.length;i++){if(fields[i].disabled||fields[i].type==='hidden')continue;if(!fields[i].checkValidity()){fields[i].reportValidity();fields[i].focus();return false}}return true}
buttons.forEach(function(b,n){b.addEventListener('click',function(){if(n<=index||valid())show(n)})});next.addEventListener('click',function(){if(valid())show(index+1)});prev.addEventListener('click',function(){show(index-1)});form.addEventListener('submit',function(e){for(var i=0;i<panels.length;i++){show(i);if(!valid()){e.preventDefault();return}}});
var seller=document.getElementById('full-seller'),newSeller=document.getElementById('new-seller-fields');function syncSeller(){newSeller.style.display=seller.value?'none':'';var option=seller.options[seller.selectedIndex];document.getElementById('side-seller').textContent=seller.value?option.text.split(' · ')[0]:(form.querySelector('[name=seller_name]').value||'New seller')};seller.addEventListener('change',syncSeller);form.querySelector('[name=seller_name]').addEventListener('input',syncSeller);syncSeller();
var device=document.getElementById('full-device'),newDevice=document.getElementById('new-device-fields'),recognized=document.getElementById('recognized-device');function syncDevice(){var option=device.options[device.selectedIndex];newDevice.style.display=device.value?'none':'';recognized.style.display=device.value?'block':'none';if(device.value){document.getElementById('recognized-device-text').textContent=option.dataset.device+' · '+option.dataset.model;var history='Current Passport state: '+(option.dataset.state||'Recorded');if(option.dataset.soldAt){history+=' · Previously sold '+option.dataset.soldAt}document.getElementById('recognized-device-history').textContent=history}document.getElementById('side-device').textContent=device.value?option.dataset.device:(document.getElementById('full-brand').value+' '+document.getElementById('full-model').value).trim()||'New Device'}device.addEventListener('change',syncDevice);document.getElementById('full-brand').addEventListener('input',syncDevice);document.getElementById('full-model').addEventListener('input',syncDevice);syncDevice();
[].slice.call(form.querySelectorAll('[name=acquisition_type]')).forEach(function(r){r.addEventListener('change',function(){document.getElementById('side-mode').textContent=r.value==='TRADE_IN'?'Trade-In':'Sell Device'})});document.getElementById('basic-pass').addEventListener('click',function(){[].slice.call(form.querySelectorAll('[data-basic-functional]')).forEach(function(s){s.value='PASS'})});
var evidence=[].slice.call(form.querySelectorAll('.evidence-amount')),reference=document.getElementById('market-reference'),guidance=document.getElementById('market-guidance');function money(v){return 'RM '+Number(v).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}function syncMarket(){var values=evidence.map(function(e){return Number(e.value)});if(values.some(function(v,i){return !evidence[i].value||!Number.isFinite(v)})){reference.setCustomValidity('');guidance.textContent='Enter both evidence prices to establish the allowed market-reference range.';return}var low=Math.min.apply(Math,values),high=Math.max.apply(Math,values),current=Number(reference.value);reference.min=low;reference.max=high;if(reference.value&&(current<low||current>high)){reference.setCustomValidity('Market reference must stay within the evidence range.');guidance.className='sb-ti-callout warning';guidance.textContent='Choose a market reference from '+money(low)+' to '+money(high)+'.'}else{reference.setCustomValidity('');guidance.className='sb-ti-callout success';guidance.textContent='Permitted market-reference range: '+money(low)+' to '+money(high)+'.'}}evidence.forEach(function(e){e.addEventListener('input',syncMarket)});reference.addEventListener('input',syncMarket);show(0);
})();
</script>
@endif
