@php
    $intake=$selectedIntake;
    $valuation=$intake->valuation;
    $latestOffer=$intake->offers->sortByDesc('offer_version')->first();
    $estimate=(array)$intake->indicative_snapshot_json;
    $evidence=(array)$intake->evidence_references_json;
    $ai=$intake->photoAiAnalyses->sortByDesc('analysis_version')->first();
    $photoAiStaffEnabled=(bool)config('recommerce.photo_ai.staff_enabled',false);
    $aiResult=(array)optional($ai)->result_json;
    $aiObservations=collect((array)($aiResult['observations']??[]));
    $technicianFindings=collect((array)data_get(optional($ai)->review,'technician_findings_json',[]))->keyBy('observation');
    $disagreements=collect((array)data_get(optional($ai)->review,'disagreements_json',[]))->keyBy('observation');
    $money=static fn($value)=>number_format((float)$value,2);
@endphp
<div class="sb-ti-workspace">
<main class="sb-ti-workspace-main">
    <div class="sb-ti-callout"><strong>Website submission · {{ $intake->external_case_reference }}</strong><br>POS case {{ $intake->intake_uuid }}. Submission {{ $intake->submission_id }} v{{ $intake->submission_version }} is immutable. Request submission is not physical receipt, approval, acquisition, or payment.</div>
    <div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>Customer submission</h2><p>{{ $intake->customer_name }} · {{ $intake->customer_email }} · {{ $intake->customer_phone }}</p></div><span class="sb-ti-badge info">Website</span></div><div class="sb-ti-panel-body">
        <div class="row"><div class="col-sm-6"><h4>{{ trim($intake->brand.' '.$intake->model) }}</h4><p>Category: {{ $intake->category_code }}</p><p>Preferred branch: {{ $intake->preferred_branch ?: 'Not supplied' }}</p></div><div class="col-sm-6"><h4>Specifications</h4>@forelse((array)$intake->specifications_json as $key=>$value)<div class="sb-ti-summary-row"><span>{{ ucwords(str_replace('_',' ',$key)) }}</span><strong>{{ is_scalar($value)?$value:'Recorded' }}</strong></div>@empty<p class="text-muted">No structured specifications supplied.</p>@endforelse</div></div>
        <hr><h4>Customer-declared condition</h4>@forelse((array)$intake->declared_condition_json as $key=>$value)<span class="label label-default" style="margin-right:6px">{{ ucwords(str_replace('_',' ',$key)) }}: {{ is_scalar($value)?$value:'Recorded' }}</span>@empty<p class="text-muted">No declaration fields supplied.</p>@endforelse
    </div></div>
    @if($photoAiStaffEnabled)<div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>AI Pre-Inspection</h2><p>Photo observations only. Customer confirmation and technician findings remain separate.</p></div><span class="sb-ti-badge info">Non-authoritative</span></div><div class="sb-ti-panel-body">
        @if($ai)
            @php $device=(array)($aiResult['device']??[]); $grade=(array)($aiResult['cosmetic_grade']??[]); @endphp
            <div class="row"><div class="col-sm-6"><h4>Likely device</h4><p><strong>{{ trim(data_get($device,'brand.value').' '.data_get($device,'model.value')) ?: 'Insufficient evidence' }}</strong><br>Model confidence: {{ round(((float)data_get($device,'model.confidence',0))*100) }}%<br>Analysis v{{ $ai->analysis_version }} · {{ $ai->provider }} / {{ $ai->model_version }}</p></div><div class="col-sm-6"><h4>Governed resolution</h4><p>Catalogue match: <strong>{{ $ai->catalogue_match_status }}</strong><br>Identity resolver: <strong>{{ str_replace('_',' ',$ai->identity_resolution_status) }}</strong><br>Cosmetic suggestion: <strong>{{ str_replace('_',' ',$grade['result']??'UNKNOWN') }}</strong> ({{ round(((float)($grade['confidence']??0))*100) }}%)</p></div></div>
            @if($ai->catalogue_match_status==='EXACT')<div class="sb-ti-callout"><strong>Existing catalogue resolver found an exact candidate.</strong><br>Product #{{ $ai->matched_product_id }} · Variation #{{ $ai->matched_variation_id }}. This is not yet the intake's authoritative native mapping.</div>@elseif(in_array($ai->catalogue_match_status,['PROBABLE','AMBIGUOUS'],true))<div class="sb-ti-callout warning"><strong>{{ ucfirst(strtolower($ai->catalogue_match_status)) }} catalogue match.</strong><br>Staff must choose through the existing catalogue/native valuation workflow.</div>@endif
            @if(!empty($aiResult['identifiers']))<p class="help-block">OCR manufacturer identifiers were passed through DeviceIdentityResolver as unverified evidence. No Device was created from OCR.</p>@endif
            <div class="table-responsive"><table class="table table-condensed"><thead><tr><th>Attribute</th><th>Customer</th><th>AI observation</th><th>Technician</th><th>Evaluation</th></tr></thead><tbody>
            @forelse($aiObservations as $observation)@php $key=$observation['observation']; $finding=$technicianFindings->get($key); $evaluation=$disagreements->get($key); @endphp<tr><td>{{ ucwords(str_replace('_',' ',$key)) }}</td><td>{{ $key==='screen_crack' ? data_get($intake->declared_condition_json,'screen','Not declared') : data_get($intake->declared_condition_json,'physical','Not declared') }}</td><td>{{ str_replace('_',' ',$observation['result']) }} · {{ str_replace('_',' ',$observation['severity']) }}<br><small>{{ round(((float)$observation['confidence'])*100) }}% · {{ count((array)$observation['evidence_ids']) }} photo(s)</small></td><td>{{ $finding ? str_replace('_',' ',$finding['finding']).' · '.str_replace('_',' ',$finding['severity']) : 'Not reviewed' }}</td><td>{{ $evaluation ? str_replace('_',' ',$evaluation['outcome']) : 'Pending' }}</td></tr>@empty<tr><td colspan="5">No visible-condition observations were returned.</td></tr>@endforelse
            </tbody></table></div>
            @if(!$ai->review && $canManage && $aiObservations->isNotEmpty())<form method="post" action="{{ route('recommerce.tradeins.intakes.photo_ai.review',[$intake->id,$ai->id]) }}">@csrf<h4>Technician comparison</h4><p class="help-block">Record what the physical inspection found. These findings do not accept AI output and do not replace the native valuation inspection.</p>@foreach($aiObservations as $index=>$observation)<div class="row" style="margin-bottom:8px"><input type="hidden" name="findings[{{ $index }}][observation]" value="{{ $observation['observation'] }}"><div class="col-sm-4"><strong>{{ ucwords(str_replace('_',' ',$observation['observation'])) }}</strong></div><div class="col-sm-3"><select class="form-control" name="findings[{{ $index }}][finding]" aria-label="Technician finding for {{ ucwords(str_replace('_',' ',$observation['observation'])) }}" required><option value="">Technician finding</option><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="PARTIAL">Partially present</option><option value="NOT_ASSESSABLE">Not assessable</option></select></div><div class="col-sm-3"><select class="form-control" name="findings[{{ $index }}][severity]" aria-label="Technician severity for {{ ucwords(str_replace('_',' ',$observation['observation'])) }}" required><option value="UNKNOWN">Severity unknown</option><option value="NONE">None</option><option value="MINOR">Minor</option><option value="MODERATE">Moderate</option><option value="SEVERE">Severe</option></select></div><div class="col-sm-2"><input class="form-control" name="findings[{{ $index }}][notes]" aria-label="Technician note for {{ ucwords(str_replace('_',' ',$observation['observation'])) }}" maxlength="500" placeholder="Note"></div></div>@endforeach<button class="btn btn-primary" type="submit">Record technician comparison</button></form>@endif
        @else<p class="text-muted">No customer-confirmed Photo AI analysis was submitted. Continue with the existing manual inspection workflow.</p>@endif
    </div></div>@endif
    <div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>Original indicative estimate</h2><p>Immutable evidence of what the customer saw; not authority to acquire.</p></div></div><div class="sb-ti-panel-body">
        @if($estimate)<div class="sb-ti-summary"><div class="sb-ti-summary-row"><span>Customer-visible range</span><strong>RM {{ $money(((int)data_get($estimate,'estimate_min_minor',0))/100) }}–RM {{ $money(((int)data_get($estimate,'estimate_max_minor',0))/100) }}</strong></div><div class="sb-ti-summary-row"><span>Policy</span><strong>{{ data_get($estimate,'pricing_policy_version','Recorded snapshot') }}</strong></div><div class="sb-ti-summary-row"><span>Engine</span><strong>{{ data_get($estimate,'engine_version','Recorded snapshot') }}</strong></div></div>@else<p>No instant estimate was created for this manual-category request.</p>@endif
    </div></div>
    <div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>Private customer evidence</h2><p>Retrieved server-to-server from the linked private website case. No connector credential is exposed to the browser.</p></div><span>{{ count($evidence) }} files</span></div><div class="sb-ti-panel-body">
        @forelse($evidence as $item)<figure style="display:inline-block;max-width:220px;margin:0 12px 12px 0"><img style="max-width:100%;height:auto" src="{{ route('recommerce.tradeins.intakes.evidence',[$intake->id,$item['evidence_id']]) }}" alt="{{ ucwords(strtolower(str_replace('_',' ',$item['evidence_type']??'customer'))) }} evidence"><figcaption>{{ $item['evidence_type']??'CUSTOMER' }} · Customer</figcaption></figure>@empty<p class="text-muted">No customer evidence was attached when this submission version was delivered.</p>@endforelse
    </div></div>
</main>
<aside class="sb-ti-sticky">
    <div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>POS authority</h2><p>Inspection and approval stay native.</p></div></div><div class="sb-ti-panel-body">
        @if(!$valuation)
            <div class="sb-ti-callout warning"><strong>Native assessment required</strong><br>Receive and inspect the customer-owned Device through the existing New Acquisition flow, then link its valuation here.</div>
            @if($canManage)<form method="post" action="{{ route('recommerce.tradeins.intakes.link_valuation',$intake->id) }}">@csrf<label for="website-intake-valuation-id">Native valuation ID</label><input id="website-intake-valuation-id" class="form-control" type="number" min="1" name="valuation_id" required><button class="btn btn-primary btn-block" style="margin-top:8px" type="submit">Link inspected valuation</button></form><hr><a class="btn btn-default btn-block" href="{{ route('recommerce.tradeins.create') }}">Open native intake & inspection</a>@endif
        @else
            <p><strong>Valuation TI-{{ str_pad($valuation->id,5,'0',STR_PAD_LEFT) }}</strong><br>{{ optional($valuation->device)->device_code }} · {{ $valuation->status }}<br>RM {{ $money($valuation->final_acquisition_amount) }}</p><a class="btn btn-default btn-block" href="{{ route('recommerce.tradeins.show',$valuation->id) }}">Open native Deal Desk</a>
            @if(in_array($valuation->status,['READY_TO_ACCEPT','APPROVED'],true) && (!$valuation->approval_required || $valuation->status==='APPROVED') && $canManage)
                <form method="post" action="{{ route('recommerce.tradeins.intakes.publish_offer',$intake->id) }}" style="margin-top:8px">@csrf<button class="btn btn-success btn-block" type="submit">Approve &amp; Send Final Offer</button></form><p class="help-block">Publishes an immutable customer-safe offer version. It does not imply customer acceptance or payment.</p>
            @elseif($valuation->status==='PENDING_APPROVAL')<div class="sb-ti-callout warning"><strong>Manager approval required</strong><br>Use the existing approval queue before publishing.</div>
            @endif
        @endif
    </div></div>
    <div class="sb-ti-panel"><div class="sb-ti-panel-head"><div><h2>Offer &amp; decision</h2></div></div><div class="sb-ti-panel-body">@if($latestOffer)<p>Offer <strong>{{ $latestOffer->offer_uuid }}</strong><br>Version {{ $latestOffer->offer_version }} · RM {{ $money($latestOffer->amount) }}<br>Status: {{ $latestOffer->status }}<br>Approved by user #{{ $latestOffer->approved_by }} at {{ optional($latestOffer->approved_at)->format('d M Y H:i') }}</p>@else<p>No POS-approved offer has been published.</p>@endif</div></div>
    <div class="sb-ti-callout"><strong>Authoritative boundaries</strong><br>Purchase: {{ optional(optional($valuation)->acquisition)->transaction_id ?: 'not created' }}<br>Device acquisition: {{ optional(optional($valuation)->acquisition)->device_id ?: 'not committed' }}<br>Settlement: not recorded by this website integration.</div>
</aside></div>
