@extends('layouts.app')
@section('title','Trade-In pricing evidence')
@section('content')
@include('recommerce::tradein.partials.styles')
<section class="container-fluid sb-ti" id="tradein-pricing-evidence">
@if(session('status'))<div class="alert alert-{{ data_get(session('status'), 'success') ? 'success' : 'warning' }}" role="status">{{ data_get(session('status'), 'msg') }}</div>@endif
<header class="sb-ti-header"><div><a href="{{ route('recommerce.tradeins.index') }}">← Trade-In Acquisition</a><h1>Pricing evidence</h1><p>References, market research, native stock signals and resale models. Final offers stay in the existing approval workflow.</p></div></header>
<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>Served release</h2><p>{{ $release['commit'] ?? 'Release marker unavailable' }} · {{ ($release['runtime_matches'] ?? false) ? 'Runtime file hashes match' : 'Runtime provenance needs verification' }}</p><p>Photo AI staff panel: {{ config('recommerce.photo_ai.staff_enabled')?'enabled':'disabled' }} · Market pricing: {{ config('recommerce.intelligence.market_enabled')?'enabled':'disabled' }} · Demand: {{ config('recommerce.intelligence.demand_enabled')?'enabled':'disabled' }} · Model pricing: {{ config('recommerce.intelligence.model_enabled')?'enabled':'disabled' }}</p></div></div>
<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>Reference decisions still needed</h2><p>Galaxy S22 RM1,500 and iPad 9 RM1,050 are incomplete model-level resale references. They are excluded from automatic phone/tablet quotes until exact variant scope and an applicable policy are approved.</p><h3>Matching native variations</h3>@forelse($native as $v)<p>{{ $v->product }} · {{ $v->name }} · {{ $v->sub_sku }} · Native variation {{ $v->id }}</p>@empty<p>No matching variation was found in this business.</p>@endforelse</div></div>
<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>Source access</h2><p>Facebook Marketplace, Shopee and Mudah each need a verified permission record before their evidence can be imported. Actual permissions, health and coverage appear in the source records below. A registered permission and permitted evidence are required, including for staff imports. No external collection runs in customer requests.</p></div></div>
@if($canManage)
<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>Import governed records</h2><p>Upload a JSON source permission, exact variant, approved reference, pricing policy or evidence batch. Records are versioned and audited. Existing native variation IDs are required; no catalogue or inventory is created here.</p><form method="post" enctype="multipart/form-data" action="{{ route('recommerce.tradeins.intelligence.store') }}">@csrf<input type="hidden" name="action" value="IMPORT"><label>Structured JSON document<input class="form-control" type="file" name="document" accept="application/json,.json" required></label><label>Reason / approval provenance<input class="form-control" name="reason" maxlength="500" required></label><button class="btn btn-primary" type="submit">Validate and import</button></form></div></div>
<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>Research and model jobs</h2><form method="post" action="{{ route('recommerce.tradeins.intelligence.store') }}">@csrf<label>Action<select class="form-control" name="action"><option value="REFRESH">Refresh market snapshot</option><option value="SIGNALS">Refresh native stock signals</option><option value="TRAIN">Extract and train resale candidate</option><option value="PROMOTE">Promote eligible model</option><option value="ROLLBACK">Roll back to reference pricing</option></select></label><label>Exact variant ID (refresh) or resale (training)<input class="form-control" name="target" value="resale"></label><label>Model record ID (promotion only)<input class="form-control" name="model_id"></label><label>Reason<input class="form-control" name="reason" required maxlength="500"></label><button class="btn btn-primary" type="submit">Record request</button></form></div></div>
@endif
@foreach($records as $kind=>$items)<div class="sb-ti-panel"><div class="sb-ti-panel-body"><h2>{{ str_replace('_',' ',ucfirst(strtolower($kind))) }}</h2>@forelse($items as $item)<details style="margin:12px 0"><summary>{{ $item['target'] }} · {{ $item['status'] }} · {{ $item['created_at'] }} · {{ $item['id'] }}</summary><p>{{ $item['reason'] }}</p><pre style="max-height:350px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere">{{ json_encode($item['data'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></details>@empty<p>No records yet. Unavailable evidence is not a zero price.</p>@endforelse</div></div>@endforeach
</section>
@endsection
