@extends('layouts.app')
@section('title', 'Stock Count')
@section('content')
<section class="container" id="stock-count-session" data-scan-url="{{ route('recommerce.stock-counts.scan', $session->id) }}" aria-labelledby="stock-count-session-title">
<div class="box box-primary"><div class="box-header with-border"><a class="btn btn-default btn-sm pull-right" href="{{ route('recommerce.stock-counts.index', ['location_id' => $session->location_id]) }}">All counts</a><h3 id="stock-count-session-title" class="box-title">Stock Count SC-{{ str_pad($session->id, 6, '0', STR_PAD_LEFT) }}</h3><p class="text-muted" style="margin:6px 0 0">{{ $session->count_type === 'FULL_BRANCH' ? 'Full branch' : 'Cycle count' }} · {{ ucwords(strtolower(str_replace('_', ' ', $session->status))) }}@if($session->snapshot_at) · Snapshot {{ $session->snapshot_at->format('d M Y H:i') }}@endif</p></div>
<div class="box-body">
@php($blind = $session->blind_count && $session->status === 'IN_PROGRESS')<div class="row"><div class="col-sm-3"><div class="info-box"><span class="info-box-icon bg-green"><i class="fa fa-qrcode"></i></span><div class="info-box-content"><span class="info-box-text">Serialized Devices</span><span class="info-box-number">{{ $summary['serialized_counted'] }} / {{ $blind ? 'Hidden' : $summary['serialized_expected'] }}</span></div></div></div><div class="col-sm-3"><div class="info-box"><span class="info-box-icon bg-aqua"><i class="fa fa-cubes"></i></span><div class="info-box-content"><span class="info-box-text">Generic Units</span><span class="info-box-number">{{ $summary['non_serialized_counted'] }} / {{ $blind ? 'Hidden' : $summary['non_serialized_expected'] }}</span></div></div></div><div class="col-sm-3"><div class="info-box"><span class="info-box-icon bg-yellow"><i class="fa fa-exclamation-triangle"></i></span><div class="info-box-content"><span class="info-box-text">Exceptions</span><span class="info-box-number">{{ $summary['open_exceptions'] }}</span></div></div></div><div class="col-sm-3"><div class="info-box"><span class="info-box-icon bg-purple"><i class="fa fa-history"></i></span><div class="info-box-content"><span class="info-box-text">Movement awareness</span><span class="info-box-number">{{ $summary['movements_since_snapshot'] }}</span></div></div></div></div>
@if($session->status === 'DRAFT')<form method="post" action="{{ route('recommerce.stock-counts.start', $session->id) }}">@csrf<button class="btn btn-primary btn-lg">Start Count &amp; Freeze Snapshot</button></form>@endif
@if($session->status === 'IN_PROGRESS')<div class="well well-lg"><label for="stock-count-scan" class="control-label">Scan Device</label><form id="stock-count-scan-form"><div class="input-group"><input id="stock-count-scan" class="form-control input-lg" autocomplete="off" autofocus placeholder="Scan QR / Device ID"><span class="input-group-btn"><button class="btn btn-primary btn-lg">Count</button></span></div></form><div id="stock-count-result" class="alert" style="display:none;margin-top:12px" role="status" aria-live="polite"></div></div>@endif
@if($session->status === 'IN_PROGRESS')<h4>Non-serialized quantities</h4><div class="table-responsive"><table class="table"><thead><tr><th>Product</th><th>Expected</th><th>Physical count</th><th></th></tr></thead><tbody>@foreach($session->items->where('item_kind','NON_SERIALIZED_VARIATION') as $item)<tr><td>{{ $item->snapshot_json['product'] ?? 'Product' }}<br><small>{{ $item->snapshot_json['variation'] ?? '' }}</small></td><td>{{ $blind ? 'Hidden' : $item->expected_quantity }}</td><td><form class="form-inline" method="post" action="{{ route('recommerce.stock-counts.quantity', [$session->id, $item->id]) }}">@csrf<input aria-label="Physical count for {{ $item->snapshot_json['product'] ?? 'product' }}" type="number" min="0" step="0.0001" name="quantity" class="form-control" value="{{ $item->counted_quantity }}"> <button class="btn btn-default">Save</button></form></td></tr>@endforeach</tbody></table></div><form method="post" action="{{ route('recommerce.stock-counts.review', $session->id) }}">@csrf<button class="btn btn-warning">Review exceptions</button></form>@endif
@if(in_array($session->status, ['REVIEW','AWAITING_APPROVAL']))<h4>Exception review</h4><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Issue</th><th>Device / product</th><th>Status</th><th>Resolution</th></tr></thead><tbody>@forelse($session->exceptions as $exception)<tr><td>{{ ucwords(strtolower(str_replace('_',' ', $exception->exception_type))) }}<br><small class="text-muted">{{ $exception->severity }}</small></td><td>@if($exception->device_id){{ optional(optional($session->items->firstWhere('device_id',$exception->device_id))->device)->device_code ?: 'Device '.$exception->device_id }}@else{{ $exception->context_json['variation_id'] ?? 'Count scope' }}@endif</td><td>{{ ucwords(strtolower($exception->status)) }}</td><td>@if($exception->status === 'OPEN')<form method="post" action="{{ route('recommerce.stock-counts.resolve', [$session->id, $exception->id]) }}">@csrf<div class="input-group"><select aria-label="Resolution reason" class="form-control" name="resolution_code"><option value="MISCOUNT">Miscount</option><option value="PREVIOUS_RECEIVING_ERROR">Previous receiving error</option><option value="UNRECORDED_INTERNAL_MOVEMENT">Unrecorded internal movement</option><option value="LOSS">Loss</option><option value="THEFT_OR_SECURITY_INCIDENT">Theft or security incident</option><option value="OTHER">Other</option></select><input aria-label="Investigation note" class="form-control" required name="resolution_note" placeholder="Investigation note"><span class="input-group-btn"><button class="btn btn-default">Record</button></span></div></form>@else{{ $exception->resolution_code }}<br><small>{{ $exception->resolution_note }}</small>@endif</td></tr>@empty<tr><td colspan="4" class="text-muted">No exceptions.</td></tr>@endforelse</tbody></table></div>
<div class="btn-group">@if($session->status === 'REVIEW')<form style="display:inline" method="post" action="{{ route('recommerce.stock-counts.submit', $session->id) }}">@csrf<button class="btn btn-warning">Submit for approval</button></form>@endif @if($session->status === 'AWAITING_APPROVAL' && !$session->approved_at)<form style="display:inline" method="post" action="{{ route('recommerce.stock-counts.approve', $session->id) }}">@csrf<button class="btn btn-primary">Approve count</button></form>@endif @if($session->status === 'REVIEW' || ($session->status === 'AWAITING_APPROVAL' && $session->approved_at))<form style="display:inline" method="post" action="{{ route('recommerce.stock-counts.reconcile', $session->id) }}">@csrf<button class="btn btn-success">Reconcile</button></form>@endif</div>@endif
@if($session->status === 'RECONCILED')<form method="post" action="{{ route('recommerce.stock-counts.close', $session->id) }}">@csrf<button class="btn btn-success">Close Count</button></form>@endif
@if($remaining->isNotEmpty() && !$session->blind_count)<h4 style="margin-top:20px">Remaining Devices</h4><ul class="list-group">@foreach($remaining as $item)<li class="list-group-item"><strong>{{ optional($item->device)->device_code ?? ($item->snapshot_json['device_code'] ?? 'Device') }}</strong> · {{ $item->snapshot_json['product'] ?? 'Product' }} <span class="text-muted">Expected at this branch · {{ $item->snapshot_json['lifecycle_state'] ?? '' }}</span></li>@endforeach</ul>@endif
@if($movements->isNotEmpty())<div class="alert alert-warning" style="margin-top:18px"><strong>Movement review required.</strong> {{ $movements->count() }} tracked Device movement(s) occurred after the snapshot. This V1 count will not automatically adjust for them or reconcile while they exist.</div>@endif
@if($session->status === 'CLOSED')<div class="alert alert-success" style="margin-top:18px"><strong>Closed and read-only.</strong> Snapshot, scans, resolutions, and audit evidence are preserved.</div>@endif
</div></div></section>
@if($session->status === 'IN_PROGRESS')<script>(() => { const input=document.getElementById('stock-count-scan'), form=document.getElementById('stock-count-scan-form'), result=document.getElementById('stock-count-result'), root=document.getElementById('stock-count-session'); const show=(text,kind)=>{result.textContent=text;result.className='alert alert-'+kind;result.style.display='block'}; form.addEventListener('submit',async(e)=>{e.preventDefault();const value=input.value.trim();if(!value)return; input.disabled=true;try{const res=await fetch(root.dataset.scanUrl,{method:'POST',credentials:'same-origin',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({value})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Scan was rejected.');const device=data.device?` ${data.device.device_code}${data.device.product?' · '+data.device.product:''}`:'';show((data.message||data.result)+device,data.result==='EXPECTED'?'success':data.result==='DUPLICATE'?'info':'warning');input.value='';}catch(error){show(error.message||'Scan was rejected.','warning')}finally{input.disabled=false;input.focus();}}); input.focus();})();</script>@endif
@endsection
